
package soap.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LaterCount", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/401_7-1/LaterCounter?wsdl")
public class LaterCount
    extends Service
{

    private final static URL LATERCOUNT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(soap.jaxws.LaterCount.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = soap.jaxws.LaterCount.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/401_7-1/LaterCounter?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/401_7-1/LaterCounter?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LATERCOUNT_WSDL_LOCATION = url;
    }

    public LaterCount(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LaterCount() {
        super(LATERCOUNT_WSDL_LOCATION, new QName("http://soap/", "LaterCount"));
    }

    /**
     * 
     * @return
     *     returns LaterCounter
     */
    @WebEndpoint(name = "LaterCounterPort")
    public LaterCounter getLaterCounterPort() {
        return super.getPort(new QName("http://soap/", "LaterCounterPort"), LaterCounter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LaterCounter
     */
    @WebEndpoint(name = "LaterCounterPort")
    public LaterCounter getLaterCounterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "LaterCounterPort"), LaterCounter.class, features);
    }

}
